In [1]:
import numpy as np

In [16]:
x=np.array([1,2,3,4,5]) 
N=5 
matrix = np.column_stack([x**(N-i-1) for i in range(N)]) 
print(matrix)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [49]:
def movingavg(l,k) :
    j=0
    l1=[]
    for j in range(len(l)-k+1) :
        s=0
        for i in range(j,j+k):
            s=s+l[i]
        l1.append(s/k)   
    print(l1)
    
movingavg([1,2,3,4,5,6,7,8,9],3)

[2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]
